global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'journey-service'
    static_configs:
      - targets: ['journey-service:9090']

  - job_name: 'report-service'
    static_configs:
      - targets: ['report-service:9090']

  - job_name: 'file-service'
    static_configs:
      - targets: ['file-service:9090']